CREATE TABLE [switch].[Sagsopgavelinjer]
(
    [Sagsopgavelinjer_Key] BIGINT NULL,
    [Job_No] NVARCHAR(MAX) NULL,
    [Job_Task_No] NVARCHAR(MAX) NULL,
    [Description] NVARCHAR(MAX) NULL,
    [Job_Task_Type] NVARCHAR(MAX) NULL,
    [Totaling] NVARCHAR(MAX) NULL,
    [Job_Posting_Group] NVARCHAR(MAX) NULL,
    [Location_Code] NVARCHAR(MAX) NULL,
    [Bin_Code] NVARCHAR(MAX) NULL,
    [WIP_Total] NVARCHAR(MAX) NULL,
    [WIP_Method] NVARCHAR(MAX) NULL,
    [Schedule_Total_Cost] FLOAT NULL,
    [Schedule_Total_Price] FLOAT NULL,
    [Usage_Total_Cost] FLOAT NULL,
    [Usage_Total_Price] FLOAT NULL,
    [Contract_Total_Cost] FLOAT NULL,
    [Contract_Total_Price] FLOAT NULL,
    [Contract_Invoiced_Cost] FLOAT NULL,
    [Contract_Invoiced_Price] FLOAT NULL,
    [Remaining_Total_Cost] FLOAT NULL,
    [Remaining_Total_Price] FLOAT NULL,
    [EAC_Total_Cost] FLOAT NULL,
    [EAC_Total_Price] FLOAT NULL,
    [Global_Dimension_1_Code] NVARCHAR(MAX) NULL,
    [Global_Dimension_2_Code] NVARCHAR(MAX) NULL,
    [Outstanding_Orders] BIGINT NULL,
    [Amt_Rcd_Not_Invoiced] BIGINT NULL,
    [Coupled_to_Dataverse] BIT NULL,
    [Planning_Date_Filter] NVARCHAR(MAX) NULL,
    [Posting_Date_Filter] NVARCHAR(MAX) NULL,
    [Company] VARCHAR(100) NULL,
    [Start_Date] DATE NULL,
    [End_Date] DATE NULL
);
GO
